### PR TITLE
UserSettings  delete

### PR DESCRIPTION
**Pull request by ramen4598**
[Bug fix]

### CODE REVIEW

**Comment by Arkru1204** [comment]
좋아요^^

**Comment by Kim-Yundong-KYD** [comment]
굿굿~!

**Review by Kim-Yundong-KYD — COMMENTED** [review]
굿굿~!

**Review by Arkru1204 — COMMENTED** [review]
굿굿-^^

**Review by Arkru1204 — COMMENTED** [review]
좋아용~~

**Review by Kim-Yundong-KYD — APPROVED** [review]
굿굿~!

**Review by Arkru1204 — APPROVED** [review]
진짜 좋아용^^b

**Pull request merged**
